### ISSUE TITLE
creating code/markdown blocks in vim

### ISSUE THREAD

**Issue by geofflangenderfer** [goerz/ipynb_notedown.vim#4]
I experimented with creating my own codeblocks/markdown in vim itself instead of in jupyter by using (see attached png):
 
![screenshot from 2018-11-26 16-26-34](https://user-images.githubusercontent.com/7274321/49050398-1554c480-f198-11e8-96b9-02ef1d5b2eff.png)

- the plugin now fails to convert from json --> markdown. 
- I've tested other notebooks and the plugin successfully converts to markdown.

Is this a known issue? Is there some way to create codeblocks/markdown that guarantees it won't break? Or, should I stick to creating new blocks within an actual jupyter notebook?

```
vim --version

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 10 2018 21:31:58)
Included patches: 1-1453
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org`
```

```
jupyter --version

4.4.0
```

**Comment by goerz** [comment]
This should work in principle...

Please try this again with the new [`jupytext.vim` plugin](
https://github.com/goerz/jupytext.vim) that supersedes `ipynb_notedown.vim`. I tried it out with your example there, and it seems to work for me. You have to use

    ``` python

to start the code-blocks, though (if you're using `jupytext` as the conversion tool, that is, which I highly recommend)
